services:
  backend_restorant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Cambiamos la URL para Postgres
      DB_URL: jdbc:postgresql://back_resto:5432/backend_resto
      DB_USER_NAME: user_admin
      DB_PASSWORD: 321
    depends_on:
      - back_resto

  back_resto:
    image: postgres:15-alpine
    container_name: postgres_restaurant
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: 321
      POSTGRES_DB: backend_resto
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: