spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret.key=z427FcQwMSPZuFbIjNWGDqUpw1MEo1DG7cIOBSuI3ps
jwt.time.exp=86400000


